### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by chymian** [liquidmetal-dev/flintlock#832]
**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

**Why do you want this feature:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Skarlso** [comment]
Sadly, Weaveworks shifted its focus off of liquid metal back when it was still alive, and now, the maintainers are otherwise occupied.

I would say, it's not dead, but it isn't really maintained either.

That said, I'm sure if community interest in the project would raise, the maintainers would gladly help out. Or even review PRs. :)

**Comment by richardcase** [comment]
@chymian (and @Skarlso ) the project has been forked into a new org so that it can be community developed.

This is the new location:

https://github.com/liquidmetal-dev

**Comment by osbre** [comment]
It might be good to put the link into the `README.md` and archive this repo then. (settings -> archive)

**Comment by richardcase** [comment]
@osbre - thanks for the feedback. I am exploring some other options but will update the readme if they don't work out.

**Comment by richardcase** [comment]
@osbre @chymian  - we are in the processes of re-starting this project up as a community effort. The org will be renamed to reflect this. If you'd like to be involved please reach out.

**Comment by richardcase** [comment]
Closing this issue now.
